### ISSUE TITLE
You don't have to show button but can show widget right the way

### ISSUE THREAD

**Issue by adamkundrat** [CroplyOfficial/iotamemes#40]
@coodos @AdamCroply 

re: 
https://github.com/CroplyOfficial/iotamemes/blob/a7267777ea0d33396719e8e376aa6dc867b961d8/client/src/components/IotaButton/IotaButton.tsx#L22

If you pass attribute show="true" widget will not draw button but it'll just show the pop-up right the way....in case you want to use it, here is an example:
```
<iota-button
          address="iota12312"
          currency="EUR"
          show="true"
          type="donation">
        </iota-button>
```

or jsbin: https://jsfiddle.net/woL5dsp0/

**Comment by AdamCroply** [comment]
Awesome! That's great for a start. Thanks @adamkundrat
